id = "voucher-generator"
name = "Voucher generator"
description = "Test voucher generator"
keywords = ["discount", "voucher"]
icon = "assests/icon.svg"
version = "0.0.1"
author = "Your name"
repo = "https://github.com/yourusername/my-extension"
homepage = "https://yourwebsite.com/my-extension"
offline_ready = true
