id = "voucher-generator"
name = "Voucher generator"
description = "Test voucher generator developed by Stall"
keywords = ["discount", "voucher"]
icon = "assests/icon.svg"
version = "0.0.1"
author = "Your name"
repo = "https://github.com/Sands-45/stall-voucher-generator"
homepage = "https://github.com/Sands-45/stall-voucher-generator"
offline_ready = true
